apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
  labels:
    app: backend-api
    tier: backend
spec:
  #type: ClusterIP is a default service in k8s
  selector:
    app: backend-api
  ports:
    - name: http
      port: 8080 # ClusterIP Service Port
      targetPort: 8080 # Container Port